### ISSUE TITLE
handle "" escaping

### ISSUE THREAD

**Issue by rvagg** [dominictarr/pull-csv#1]
Newline handling is probably out of the question (who cares anyway!) but `""` escaping is pretty important for any cells containing a single `"` you get a `""` instead and are not allowed to treat that as the end-of-cell.

**Comment by dominictarr** [comment]
oh... so `"...""...""..."` becomes `..."..."...`? FML
- TODO: travel back in time and make csv use `\` for escapes.

**Comment by rvagg** [comment]
Correct

**Comment by dominictarr** [comment]
adding another testcase...

**Comment by dominictarr** [comment]
this is fixed in 1.0.2
